name: tinyImageNet_imb01
print_freq: 40
workers: 4
log_dir: 'logs'
model_dir: 'ckps'


# dataset & model setting
dataset: 'tinyImageNet'
data_path: '/kaggle/input/tiny-imagenet/tiny-imagenet-200/'
num_classes: 200
imb_factor: 0.1
backbone: 'resnet10_fe'
feat_size: 512
resume: ''
head_class_idx:
  - 0
  - 70
med_class_idx:
  - 70
  - 140
tail_class_idx:
  - 140
  - 200


# distributed training
deterministic: False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False



# Train
mode: 'stage1'
lr: 0.2
batch_size: 128
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False
mixup: False
alpha: 1.0
start_aug: 10
end_aug: 3
fit_thresh: 0.7
bank_size: 128